package projekfastfoodrestaurant;

import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * @author RICZKY PRATAMA | Tech Enthusiast | Instagram : @silver_rabbitku
 * Disclaimer : Program ini masih dengan fitur terbatas. Karena ditujukan untuk pembelajaran programer pemula.
 */
public class FastFood extends javax.swing.JFrame {
    private JFrame frame;
    
    //deklarasi atau memberi nilai harga pada masing masing variable
    //deklarasi meat dan vegetarian
    double Price_Fries = 1.1;
    double Price_Salad = 1.2;
    double Price_Hamburger = 2.27;
    double Price_OnionRings = 0.56;
    double Price_ChickenSalad = 2.2;
    
    //deklarasi sandwich
    double Price_FishSandwich = 2.7;
    double Price_CheeseSandwich = 2.2;
    double Price_ChickenSandwich = 2.2;
    
    //deklarasi dessert
    double Price_HashBrown = 2.5;
    double Price_ToastedBagel = 1.6;
    double Price_PineapleStick = 1.7;
    double Price_ChocolateMuffin = 1.8;
    double Price_PancakeSyrup = 1.2;
    
    //deklarasi drink
    double Price_Tea = 2.25;
    double Price_Cola = 0.89;
    double Price_Coffee = 1.5;
    double Price_Orange = 1.5;
    double Price_BottleWater = 1.9;
    
    //deklarasi shakes
    double Price_VanillaCone = 1.5;
    double Price_VanillaShakes = 1.7;
    double Price_StrawberryShakes = 1.4;
    double Price_ChocolateMilkShakes = 1.2;
    
    //deklarasi hasil perhitungan
    double Tax_Rate = 3.7;
    
    double iTax, iTotal, iSubTotal, iChange, iCost;
    
    double[] itemcost = new double[22]; //ini adalah array
    
    
    
    
    
    

    /**
     * Creates new form FastFood
     */
    public FastFood() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jChkFries = new javax.swing.JCheckBox();
        jChkSalad = new javax.swing.JCheckBox();
        jChkHamburger = new javax.swing.JCheckBox();
        jChkOnionRings = new javax.swing.JCheckBox();
        jChkFishSandwich = new javax.swing.JCheckBox();
        jChkCheeseSandwich = new javax.swing.JCheckBox();
        jChkChickenSandwich = new javax.swing.JCheckBox();
        jChkChickenSalad = new javax.swing.JCheckBox();
        jTxtSalad = new javax.swing.JTextField();
        jTxtHamburger = new javax.swing.JTextField();
        jTxtOnionRings = new javax.swing.JTextField();
        jTxtFishSandwich = new javax.swing.JTextField();
        jTxtCheeseSandwich = new javax.swing.JTextField();
        jTxtChickenSandwich = new javax.swing.JTextField();
        jTxtChickenSalad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtFries = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jChkHashBrown = new javax.swing.JCheckBox();
        jChkToastedBagel = new javax.swing.JCheckBox();
        jChkPineapleStick = new javax.swing.JCheckBox();
        jChkChocolateMuffin = new javax.swing.JCheckBox();
        jChkPancakeSyrup = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jTxtPancakeSyrup = new javax.swing.JTextField();
        jTxtToastedBagel = new javax.swing.JTextField();
        jTxtPineapleStick = new javax.swing.JTextField();
        jTxtChocolateMuffin = new javax.swing.JTextField();
        jTxtHashBrown = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTxtTotal = new javax.swing.JTextField();
        jTxtTax = new javax.swing.JTextField();
        jTxtSubTotal = new javax.swing.JTextField();
        jTxtChange = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jChkTea = new javax.swing.JCheckBox();
        jChkCola = new javax.swing.JCheckBox();
        jChkCoffee = new javax.swing.JCheckBox();
        jChkOrange = new javax.swing.JCheckBox();
        jChkBottleWater = new javax.swing.JCheckBox();
        jChkVanillaCone = new javax.swing.JCheckBox();
        jChkVanillaShakes = new javax.swing.JCheckBox();
        jChkChocoMilkShakes = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jTxtChocoMilkShakes = new javax.swing.JTextField();
        jTxtCola = new javax.swing.JTextField();
        jTxtCoffee = new javax.swing.JTextField();
        jTxtOrange = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jChkStrawberryShakes = new javax.swing.JCheckBox();
        jTxtBottleWater = new javax.swing.JTextField();
        jTxtVanillaCone = new javax.swing.JTextField();
        jTxtVanillaShakes = new javax.swing.JTextField();
        jTxtStrawberryShakes = new javax.swing.JTextField();
        jTxtTea = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTxtMoney = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBtnExit = new javax.swing.JButton();
        jBtnTotal = new javax.swing.JButton();
        jBtnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 720));
        setPreferredSize(new java.awt.Dimension(1025, 720));
        setSize(new java.awt.Dimension(1020, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Calibri", 3, 30)); // NOI18N
        jLabel3.setText("Fast Food Manajement System");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(330, 30, 400, 38);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ini adalah program manajemen system untuk yang cocok untuk bisnis kamu. This App Created by Riczky Pratama.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(200, 70, 650, 18);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 990, 120));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jChkFries.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jChkFries.setText("Fries");
        jChkFries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkFriesActionPerformed(evt);
            }
        });
        jPanel2.add(jChkFries, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jChkSalad.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jChkSalad.setText("Salad");
        jChkSalad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkSaladActionPerformed(evt);
            }
        });
        jPanel2.add(jChkSalad, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 116, -1, -1));

        jChkHamburger.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jChkHamburger.setText("Hamburger");
        jChkHamburger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkHamburgerActionPerformed(evt);
            }
        });
        jPanel2.add(jChkHamburger, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 160, -1, -1));

        jChkOnionRings.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jChkOnionRings.setText("Onion Rings");
        jChkOnionRings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkOnionRingsActionPerformed(evt);
            }
        });
        jPanel2.add(jChkOnionRings, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 204, -1, -1));

        jChkFishSandwich.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jChkFishSandwich.setText("Fish Sandwich");
        jChkFishSandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkFishSandwichActionPerformed(evt);
            }
        });
        jPanel2.add(jChkFishSandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 378, -1, -1));

        jChkCheeseSandwich.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jChkCheeseSandwich.setText("Cheese Sandwich");
        jChkCheeseSandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkCheeseSandwichActionPerformed(evt);
            }
        });
        jPanel2.add(jChkCheeseSandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 428, -1, -1));

        jChkChickenSandwich.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jChkChickenSandwich.setText("Chicken Sandwich");
        jChkChickenSandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkChickenSandwichActionPerformed(evt);
            }
        });
        jPanel2.add(jChkChickenSandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 475, -1, -1));

        jChkChickenSalad.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jChkChickenSalad.setText("Chicken Salad");
        jChkChickenSalad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkChickenSaladActionPerformed(evt);
            }
        });
        jPanel2.add(jChkChickenSalad, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 248, -1, -1));

        jTxtSalad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtSalad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtSalad.setText("0");
        jTxtSalad.setEnabled(false);
        jTxtSalad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtSaladKeyTyped(evt);
            }
        });
        jPanel2.add(jTxtSalad, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 116, 90, 26));

        jTxtHamburger.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtHamburger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtHamburger.setText("0");
        jTxtHamburger.setEnabled(false);
        jTxtHamburger.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtHamburgerKeyTyped(evt);
            }
        });
        jPanel2.add(jTxtHamburger, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 160, 90, 26));

        jTxtOnionRings.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtOnionRings.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtOnionRings.setText("0");
        jTxtOnionRings.setEnabled(false);
        jTxtOnionRings.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtOnionRingsKeyTyped(evt);
            }
        });
        jPanel2.add(jTxtOnionRings, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 204, 90, 26));

        jTxtFishSandwich.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtFishSandwich.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtFishSandwich.setText("0");
        jTxtFishSandwich.setEnabled(false);
        jTxtFishSandwich.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtFishSandwichKeyTyped(evt);
            }
        });
        jPanel2.add(jTxtFishSandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 378, 80, 26));

        jTxtCheeseSandwich.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtCheeseSandwich.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtCheeseSandwich.setText("0");
        jTxtCheeseSandwich.setEnabled(false);
        jTxtCheeseSandwich.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtCheeseSandwichKeyTyped(evt);
            }
        });
        jPanel2.add(jTxtCheeseSandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 428, 80, 26));

        jTxtChickenSandwich.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtChickenSandwich.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtChickenSandwich.setText("0");
        jTxtChickenSandwich.setEnabled(false);
        jTxtChickenSandwich.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtChickenSandwichKeyTyped(evt);
            }
        });
        jPanel2.add(jTxtChickenSandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 475, 80, 26));

        jTxtChickenSalad.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtChickenSalad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtChickenSalad.setText("0");
        jTxtChickenSalad.setEnabled(false);
        jTxtChickenSalad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtChickenSaladKeyTyped(evt);
            }
        });
        jPanel2.add(jTxtChickenSalad, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 248, 90, 26));

        jLabel5.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel5.setText("Fast Meal And Vegetarian");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 20, -1, -1));

        jTxtFries.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtFries.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtFries.setText("0");
        jTxtFries.setEnabled(false);
        jTxtFries.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtFriesKeyTyped(evt);
            }
        });
        jPanel2.add(jTxtFries, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 68, 90, 30));

        jLabel12.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel12.setText("Sandwich");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 330, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 300, 530));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jChkHashBrown.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jChkHashBrown.setText("Hash Brown");
        jChkHashBrown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkHashBrownActionPerformed(evt);
            }
        });
        jPanel3.add(jChkHashBrown, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jChkToastedBagel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jChkToastedBagel.setText("Toasted Bagel");
        jChkToastedBagel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkToastedBagelActionPerformed(evt);
            }
        });
        jPanel3.add(jChkToastedBagel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jChkPineapleStick.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jChkPineapleStick.setText("Pineaple Stick");
        jChkPineapleStick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkPineapleStickActionPerformed(evt);
            }
        });
        jPanel3.add(jChkPineapleStick, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jChkChocolateMuffin.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jChkChocolateMuffin.setText("Chocolate Muffin");
        jChkChocolateMuffin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkChocolateMuffinActionPerformed(evt);
            }
        });
        jPanel3.add(jChkChocolateMuffin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jChkPancakeSyrup.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jChkPancakeSyrup.setText("Pancake - Syrup");
        jChkPancakeSyrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkPancakeSyrupActionPerformed(evt);
            }
        });
        jPanel3.add(jChkPancakeSyrup, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 231, -1, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel1.setText("Desssert");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 20, -1, -1));

        jTxtPancakeSyrup.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtPancakeSyrup.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtPancakeSyrup.setText("0");
        jTxtPancakeSyrup.setEnabled(false);
        jTxtPancakeSyrup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtPancakeSyrupKeyTyped(evt);
            }
        });
        jPanel3.add(jTxtPancakeSyrup, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 90, 26));

        jTxtToastedBagel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtToastedBagel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtToastedBagel.setText("0");
        jTxtToastedBagel.setEnabled(false);
        jTxtToastedBagel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtToastedBagelKeyTyped(evt);
            }
        });
        jPanel3.add(jTxtToastedBagel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 90, 26));

        jTxtPineapleStick.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtPineapleStick.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtPineapleStick.setText("0");
        jTxtPineapleStick.setEnabled(false);
        jTxtPineapleStick.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtPineapleStickKeyTyped(evt);
            }
        });
        jPanel3.add(jTxtPineapleStick, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 90, 26));

        jTxtChocolateMuffin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtChocolateMuffin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtChocolateMuffin.setText("0");
        jTxtChocolateMuffin.setEnabled(false);
        jTxtChocolateMuffin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtChocolateMuffinKeyTyped(evt);
            }
        });
        jPanel3.add(jTxtChocolateMuffin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 90, 26));

        jTxtHashBrown.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtHashBrown.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtHashBrown.setText("0");
        jTxtHashBrown.setEnabled(false);
        jTxtHashBrown.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtHashBrownKeyTyped(evt);
            }
        });
        jPanel3.add(jTxtHashBrown, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 90, 26));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 400, 280));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel8.setText("Total");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 60, -1));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel9.setText("Change");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, -1));

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel10.setText("Tax");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, -1));

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel11.setText("Sub Total");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, -1));

        jTxtTotal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtTotal.setEnabled(false);
        jPanel4.add(jTxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 90, 26));

        jTxtTax.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtTax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtTax.setEnabled(false);
        jPanel4.add(jTxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 90, 26));

        jTxtSubTotal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtSubTotal.setEnabled(false);
        jPanel4.add(jTxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 90, 26));

        jTxtChange.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtChange.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtChange.setEnabled(false);
        jTxtChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtChangeActionPerformed(evt);
            }
        });
        jPanel4.add(jTxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 90, 26));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 220, 180));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jChkTea.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jChkTea.setText("Tea");
        jChkTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkTeaActionPerformed(evt);
            }
        });
        jPanel5.add(jChkTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jChkCola.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jChkCola.setText("Cola");
        jChkCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkColaActionPerformed(evt);
            }
        });
        jPanel5.add(jChkCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jChkCoffee.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jChkCoffee.setText("Coffee");
        jChkCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkCoffeeActionPerformed(evt);
            }
        });
        jPanel5.add(jChkCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jChkOrange.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jChkOrange.setText("Orange");
        jChkOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkOrangeActionPerformed(evt);
            }
        });
        jPanel5.add(jChkOrange, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jChkBottleWater.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jChkBottleWater.setText("Bottle Water");
        jChkBottleWater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkBottleWaterActionPerformed(evt);
            }
        });
        jPanel5.add(jChkBottleWater, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jChkVanillaCone.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jChkVanillaCone.setText("Vanilla Cone");
        jChkVanillaCone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkVanillaConeActionPerformed(evt);
            }
        });
        jPanel5.add(jChkVanillaCone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jChkVanillaShakes.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jChkVanillaShakes.setText("Vanilla S.");
        jChkVanillaShakes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkVanillaShakesActionPerformed(evt);
            }
        });
        jPanel5.add(jChkVanillaShakes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jChkChocoMilkShakes.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jChkChocoMilkShakes.setText("Choco Milk S.");
        jChkChocoMilkShakes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkChocoMilkShakesActionPerformed(evt);
            }
        });
        jPanel5.add(jChkChocoMilkShakes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel6.setText("Shakes");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 80, -1));

        jTxtChocoMilkShakes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtChocoMilkShakes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtChocoMilkShakes.setText("0");
        jTxtChocoMilkShakes.setEnabled(false);
        jTxtChocoMilkShakes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtChocoMilkShakesKeyTyped(evt);
            }
        });
        jPanel5.add(jTxtChocoMilkShakes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 90, 26));

        jTxtCola.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtCola.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtCola.setText("0");
        jTxtCola.setEnabled(false);
        jTxtCola.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtColaKeyTyped(evt);
            }
        });
        jPanel5.add(jTxtCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 90, 26));

        jTxtCoffee.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtCoffee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtCoffee.setText("0");
        jTxtCoffee.setEnabled(false);
        jTxtCoffee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtCoffeeKeyTyped(evt);
            }
        });
        jPanel5.add(jTxtCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 90, 26));

        jTxtOrange.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtOrange.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtOrange.setText("0");
        jTxtOrange.setEnabled(false);
        jTxtOrange.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtOrangeKeyTyped(evt);
            }
        });
        jPanel5.add(jTxtOrange, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 90, 26));

        jLabel7.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel7.setText("Drinks");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 20, 80, -1));

        jChkStrawberryShakes.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jChkStrawberryShakes.setText("Strawberry S.");
        jChkStrawberryShakes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkStrawberryShakesActionPerformed(evt);
            }
        });
        jPanel5.add(jChkStrawberryShakes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jTxtBottleWater.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtBottleWater.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtBottleWater.setText("0");
        jTxtBottleWater.setEnabled(false);
        jTxtBottleWater.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtBottleWaterKeyTyped(evt);
            }
        });
        jPanel5.add(jTxtBottleWater, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 90, 26));

        jTxtVanillaCone.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtVanillaCone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtVanillaCone.setText("0");
        jTxtVanillaCone.setEnabled(false);
        jTxtVanillaCone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtVanillaConeKeyTyped(evt);
            }
        });
        jPanel5.add(jTxtVanillaCone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 90, 26));

        jTxtVanillaShakes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtVanillaShakes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtVanillaShakes.setText("0");
        jTxtVanillaShakes.setEnabled(false);
        jTxtVanillaShakes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtVanillaShakesKeyTyped(evt);
            }
        });
        jPanel5.add(jTxtVanillaShakes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 90, 26));

        jTxtStrawberryShakes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtStrawberryShakes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtStrawberryShakes.setText("0");
        jTxtStrawberryShakes.setEnabled(false);
        jTxtStrawberryShakes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtStrawberryShakesKeyTyped(evt);
            }
        });
        jPanel5.add(jTxtStrawberryShakes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 90, 26));

        jTxtTea.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtTea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtTea.setText("0");
        jTxtTea.setEnabled(false);
        jTxtTea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtTeaKeyTyped(evt);
            }
        });
        jPanel5.add(jTxtTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 90, 26));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 270, 530));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4));

        jComboBox1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Debit Card", "Master Card", "Visa Card" }));

        jTxtMoney.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTxtMoney.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtMoney.setText("0");
        jTxtMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtMoneyActionPerformed(evt);
            }
        });
        jTxtMoney.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtMoneyKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 3, 20)); // NOI18N
        jLabel2.setText("Payment Method");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jTxtMoney))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTxtMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 170, 180));

        jBtnExit.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jBtnExit.setText("Exit");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 620, 110, 50));

        jBtnTotal.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jBtnTotal.setText("Total");
        jBtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTotalActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 619, 110, 50));

        jBtnReset.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jBtnReset.setText("Reset");
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 620, 110, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jChkSaladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkSaladActionPerformed
        // Ini adalah kode jika ceklish di klik maka text field akan bisa diisi, jika tidak maka sebaliknya
        if (jChkSalad.isSelected()) {
            jTxtSalad.setEnabled(true);
            jTxtSalad.requestFocus();
            jTxtSalad.setText("");
        } else {
            jTxtSalad.setEnabled(false);
            jTxtSalad.setText("0");
        }
    }//GEN-LAST:event_jChkSaladActionPerformed

    private void jChkHashBrownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkHashBrownActionPerformed
        // Ini adalah kode jika ceklish di klik maka text field akan bisa diisi, jika tidak maka sebaliknya
        if (jChkHashBrown.isSelected()) {
            jTxtHashBrown.setEnabled(true);
            jTxtHashBrown.requestFocus();
            jTxtHashBrown.setText("");
        } else {
            jTxtHashBrown.setEnabled(false);
            jTxtHashBrown.setText("0");
        }
    }//GEN-LAST:event_jChkHashBrownActionPerformed

    private void jChkPineapleStickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkPineapleStickActionPerformed
        // Ini adalah kode jika ceklish di klik maka text field akan bisa diisi, jika tidak maka sebaliknya
        if (jChkPineapleStick.isSelected()) {
            jTxtPineapleStick.setEnabled(true);
            jTxtPineapleStick.requestFocus();
            jTxtPineapleStick.setText("");
        } else {
            jTxtPineapleStick.setEnabled(false);
            jTxtPineapleStick.setText("0");
        }
    }//GEN-LAST:event_jChkPineapleStickActionPerformed

    private void jChkCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkCoffeeActionPerformed
        // Ini adalah kode jika ceklish di klik maka text field akan bisa diisi, jika tidak maka sebaliknya
        if (jChkCoffee.isSelected()) {
            jTxtCoffee.setEnabled(true);
            jTxtCoffee.requestFocus();
            jTxtCoffee.setText("");
        } else {
            jTxtCoffee.setEnabled(false);
            jTxtCoffee.setText("0");
        }
    }//GEN-LAST:event_jChkCoffeeActionPerformed

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        // TODO add your handling code here:
        
        //Inisiasi frame exit
        frame = new JFrame("Exit");
        
        // Ini adalah tombol exit
        if (JOptionPane.showConfirmDialog(frame, "Apakah Kamu ingin Keluar?", "Fast Food", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
        // TODO add your handling code here:
        
        // Ini adalah untuk tombol Reset
        
        //Untuk mereset TxtField menjadi kosong
        //===================================//
        jTxtBottleWater.setText(null);
        jTxtChange.setText(null);
        jTxtCheeseSandwich.setText(null);
        jTxtChickenSalad.setText(null);
        jTxtChickenSandwich.setText(null);
        jTxtChocoMilkShakes.setText(null);
        jTxtChocolateMuffin.setText(null);
        jTxtCoffee.setText(null);
        jTxtCola.setText(null);
        jTxtFishSandwich.setText(null);
        jTxtFries.setText(null);
        jTxtHamburger.setText(null);
        jTxtHashBrown.setText(null);
        jTxtOnionRings.setText(null);
        jTxtOrange.setText(null);
        jTxtPancakeSyrup.setText(null);
        jTxtPineapleStick.setText(null);
        jTxtSalad.setText(null);
        jTxtStrawberryShakes.setText(null);
        jTxtSubTotal.setText(null);
        jTxtTax.setText(null);
        jTxtTea.setText(null);
        jTxtToastedBagel.setText(null);
        jTxtTotal.setText(null);
        jTxtVanillaCone.setText(null);
        jTxtVanillaShakes.setText(null);
        jTxtMoney.setText(null);
        //==========================//
        
        //Untuk mereset jChecklist menjadi kosong
        //==========================//
        //-fastmealandvegetarian-//
        jChkFries.setSelected(false);
        jChkSalad.setSelected(false);
        jChkHamburger.setSelected(false);
        jChkOnionRings.setSelected(false);
        jChkChickenSalad.setSelected(false);
        //-sandwich-//
        jChkFishSandwich.setSelected(false);
        jChkCheeseSandwich.setSelected(false);
        jChkChickenSandwich.setSelected(false);
        //-dessert-//
        jChkHashBrown.setSelected(false);
        jChkToastedBagel.setSelected(false);
        jChkPineapleStick.setSelected(false);
        jChkChocolateMuffin.setSelected(false);
        jChkPancakeSyrup.setSelected(false);
        //-drinks-//
        jChkTea.setSelected(false);
        jChkCola.setSelected(false);
        jChkCoffee.setSelected(false);
        jChkOrange.setSelected(false);
        jChkBottleWater.setSelected(false);
        //-shakes-//
        jChkVanillaCone.setSelected(false);
        jChkVanillaShakes.setSelected(false);
        jChkStrawberryShakes.setSelected(false);
        jChkChocoMilkShakes.setSelected(false);
        //==========================//
    }//GEN-LAST:event_jBtnResetActionPerformed

    private void jTxtFriesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFriesKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtFriesKeyTyped

    private void jTxtSaladKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtSaladKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtSaladKeyTyped

    private void jTxtHamburgerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtHamburgerKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtHamburgerKeyTyped

    private void jTxtOnionRingsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtOnionRingsKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtOnionRingsKeyTyped

    private void jTxtChickenSaladKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtChickenSaladKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtChickenSaladKeyTyped

    private void jTxtFishSandwichKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFishSandwichKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtFishSandwichKeyTyped

    private void jTxtCheeseSandwichKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCheeseSandwichKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtCheeseSandwichKeyTyped

    private void jTxtChickenSandwichKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtChickenSandwichKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtChickenSandwichKeyTyped

    private void jTxtHashBrownKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtHashBrownKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtHashBrownKeyTyped

    private void jTxtToastedBagelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtToastedBagelKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtToastedBagelKeyTyped

    private void jTxtPineapleStickKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPineapleStickKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtPineapleStickKeyTyped

    private void jTxtChocolateMuffinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtChocolateMuffinKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtChocolateMuffinKeyTyped

    private void jTxtPancakeSyrupKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPancakeSyrupKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtPancakeSyrupKeyTyped

    private void jTxtTeaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtTeaKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtTeaKeyTyped

    private void jTxtColaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtColaKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtColaKeyTyped

    private void jTxtCoffeeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCoffeeKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtCoffeeKeyTyped

    private void jTxtOrangeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtOrangeKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtOrangeKeyTyped

    private void jTxtBottleWaterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtBottleWaterKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtBottleWaterKeyTyped

    private void jTxtVanillaConeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtVanillaConeKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtVanillaConeKeyTyped

    private void jTxtVanillaShakesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtVanillaShakesKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtVanillaShakesKeyTyped

    private void jTxtStrawberryShakesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtStrawberryShakesKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtStrawberryShakesKeyTyped

    private void jTxtChocoMilkShakesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtChocoMilkShakesKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtChocoMilkShakesKeyTyped

    private void jTxtMoneyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtMoneyKeyTyped
        // Ini adalah kode agar user tidak bisa memasukan karakter selain angka
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtMoneyKeyTyped

    private void jChkFriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkFriesActionPerformed
        // Ini adalah kode jika ceklish di klik maka text field akan bisa diisi, jika tidak maka sebaliknya
        if (jChkFries.isSelected()) {
            jTxtFries.setEnabled(true);
            jTxtFries.requestFocus();
            jTxtFries.setText("");
        } else {
            jTxtFries.setEnabled(false);
            jTxtFries.setText("0");
        }
    }//GEN-LAST:event_jChkFriesActionPerformed

    private void jChkHamburgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkHamburgerActionPerformed
        // Ini adalah kode jika ceklish di klik maka text field akan bisa diisi, jika tidak maka sebaliknya
        if (jChkHamburger.isSelected()) {
            jTxtHamburger.setEnabled(true);
            jTxtHamburger.requestFocus();
            jTxtHamburger.setText("");
        } else {
            jTxtHamburger.setEnabled(false);
            jTxtHamburger.setText("0");
        }
    }//GEN-LAST:event_jChkHamburgerActionPerformed

    private void jChkOnionRingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkOnionRingsActionPerformed
        // Ini adalah kode jika ceklish di klik maka text field akan bisa diisi, jika tidak maka sebaliknya
        if (jChkOnionRings.isSelected()) {
            jTxtOnionRings.setEnabled(true);
            jTxtOnionRings.requestFocus();
            jTxtOnionRings.setText("");
        } else {
            jTxtOnionRings.setEnabled(false);
            jTxtOnionRings.setText("0");
        }
    }//GEN-LAST:event_jChkOnionRingsActionPerformed

    private void jChkChickenSaladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkChickenSaladActionPerformed
        // Ini adalah kode jika ceklish di klik maka text field akan bisa diisi, jika tidak maka sebaliknya
        if (jChkChickenSalad.isSelected()) {
            jTxtChickenSalad.setEnabled(true);
            jTxtChickenSalad.requestFocus();
            jTxtChickenSalad.setText("");
        } else {
            jTxtChickenSalad.setEnabled(false);
            jTxtChickenSalad.setText("0");
        }
    }//GEN-LAST:event_jChkChickenSaladActionPerformed

    private void jChkFishSandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkFishSandwichActionPerformed
        // Ini adalah kode jika ceklish di klik maka text field akan bisa diisi, jika tidak maka sebaliknya
        if (jChkFishSandwich.isSelected()) {
            jTxtFishSandwich.setEnabled(true);
            jTxtFishSandwich.requestFocus();
            jTxtFishSandwich.setText("");
        } else {
            jTxtFishSandwich.setEnabled(false);
            jTxtFishSandwich.setText("0");
        }
    }//GEN-LAST:event_jChkFishSandwichActionPerformed

    private void jChkCheeseSandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkCheeseSandwichActionPerformed
        // Ini adalah kode jika ceklish di klik maka text field akan bisa diisi, jika tidak maka sebaliknya
        if (jChkCheeseSandwich.isSelected()) {
            jTxtCheeseSandwich.setEnabled(true);
            jTxtCheeseSandwich.requestFocus();
            jTxtCheeseSandwich.setText("");
        } else {
            jTxtCheeseSandwich.setEnabled(false);
            jTxtCheeseSandwich.setText("0");
        }
    }//GEN-LAST:event_jChkCheeseSandwichActionPerformed

    private void jChkChickenSandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkChickenSandwichActionPerformed
        // Ini adalah kode jika ceklish di klik maka text field akan bisa diisi, jika tidak maka sebaliknya
        if (jChkChickenSandwich.isSelected()) {
            jTxtChickenSandwich.setEnabled(true);
            jTxtChickenSandwich.requestFocus();
            jTxtChickenSandwich.setText("");
        } else {
            jTxtChickenSandwich.setEnabled(false);
            jTxtChickenSandwich.setText("0");
        }
    }//GEN-LAST:event_jChkChickenSandwichActionPerformed

    private void jChkToastedBagelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkToastedBagelActionPerformed
        // Ini adalah kode jika ceklish di klik maka text field akan bisa diisi, jika tidak maka sebaliknya
        if (jChkToastedBagel.isSelected()) {
            jTxtToastedBagel.setEnabled(true);
            jTxtToastedBagel.requestFocus();
            jTxtToastedBagel.setText("");
        } else {
            jTxtToastedBagel.setEnabled(false);
            jTxtToastedBagel.setText("0");
        }
    }//GEN-LAST:event_jChkToastedBagelActionPerformed

    private void jChkChocolateMuffinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkChocolateMuffinActionPerformed
        // Ini adalah kode jika ceklish di klik maka text field akan bisa diisi, jika tidak maka sebaliknya
        if (jChkChocolateMuffin.isSelected()) {
            jTxtChocolateMuffin.setEnabled(true);
            jTxtChocolateMuffin.requestFocus();
            jTxtChocolateMuffin.setText("");
        } else {
            jTxtChocolateMuffin.setEnabled(false);
            jTxtChocolateMuffin.setText("0");
        }
    }//GEN-LAST:event_jChkChocolateMuffinActionPerformed

    private void jChkPancakeSyrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkPancakeSyrupActionPerformed
        // Ini adalah kode jika ceklish di klik maka text field akan bisa diisi, jika tidak maka sebaliknya
        if (jChkPancakeSyrup.isSelected()) {
            jTxtPancakeSyrup.setEnabled(true);
            jTxtPancakeSyrup.requestFocus();
            jTxtPancakeSyrup.setText("");
        } else {
            jTxtPancakeSyrup.setEnabled(false);
            jTxtPancakeSyrup.setText("0");
        }
    }//GEN-LAST:event_jChkPancakeSyrupActionPerformed

    private void jChkTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkTeaActionPerformed
        // Ini adalah kode jika ceklish di klik maka text field akan bisa diisi, jika tidak maka sebaliknya
        if (jChkTea.isSelected()) {
            jTxtTea.setEnabled(true);
            jTxtTea.requestFocus();
            jTxtTea.setText("");
        } else {
            jTxtTea.setEnabled(false);
            jTxtTea.setText("0");
        }
    }//GEN-LAST:event_jChkTeaActionPerformed

    private void jChkColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkColaActionPerformed
        // Ini adalah kode jika ceklish di klik maka text field akan bisa diisi, jika tidak maka sebaliknya
        if (jChkCola.isSelected()) {
            jTxtCola.setEnabled(true);
            jTxtCola.requestFocus();
            jTxtCola.setText("");
        } else {
            jTxtCola.setEnabled(false);
            jTxtCola.setText("0");
        }
    }//GEN-LAST:event_jChkColaActionPerformed

    private void jChkOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkOrangeActionPerformed
        // Ini adalah kode jika ceklish di klik maka text field akan bisa diisi, jika tidak maka sebaliknya
        if (jChkOrange.isSelected()) {
            jTxtOrange.setEnabled(true);
            jTxtOrange.requestFocus();
            jTxtOrange.setText("");
        } else {
            jTxtOrange.setEnabled(false);
            jTxtOrange.setText("0");
        }
    }//GEN-LAST:event_jChkOrangeActionPerformed

    private void jChkBottleWaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkBottleWaterActionPerformed
        // Ini adalah kode jika ceklish di klik maka text field akan bisa diisi, jika tidak maka sebaliknya
        if (jChkBottleWater.isSelected()) {
            jTxtBottleWater.setEnabled(true);
            jTxtBottleWater.requestFocus();
            jTxtBottleWater.setText("");
        } else {
            jTxtBottleWater.setEnabled(false);
            jTxtBottleWater.setText("0");
        }
    }//GEN-LAST:event_jChkBottleWaterActionPerformed

    private void jChkVanillaConeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkVanillaConeActionPerformed
        // Ini adalah kode jika ceklish di klik maka text field akan bisa diisi, jika tidak maka sebaliknya
        if (jChkVanillaCone.isSelected()) {
            jTxtVanillaCone.setEnabled(true);
            jTxtVanillaCone.requestFocus();
            jTxtVanillaCone.setText("");
        } else {
            jTxtVanillaCone.setEnabled(false);
            jTxtVanillaCone.setText("0");
        }
    }//GEN-LAST:event_jChkVanillaConeActionPerformed

    private void jChkVanillaShakesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkVanillaShakesActionPerformed
        // Ini adalah kode jika ceklish di klik maka text field akan bisa diisi, jika tidak maka sebaliknya
        if (jChkVanillaShakes.isSelected()) {
            jTxtVanillaShakes.setEnabled(true);
            jTxtVanillaShakes.requestFocus();
            jTxtVanillaShakes.setText("");
        } else {
            jTxtVanillaShakes.setEnabled(false);
            jTxtVanillaShakes.setText("0");
        }
    }//GEN-LAST:event_jChkVanillaShakesActionPerformed

    private void jChkStrawberryShakesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkStrawberryShakesActionPerformed
        // Ini adalah kode jika ceklish di klik maka text field akan bisa diisi, jika tidak maka sebaliknya
        if (jChkStrawberryShakes.isSelected()) {
            jTxtStrawberryShakes.setEnabled(true);
            jTxtStrawberryShakes.requestFocus();
            jTxtStrawberryShakes.setText("");
        } else {
            jTxtStrawberryShakes.setEnabled(false);
            jTxtStrawberryShakes.setText("0");
        }
    }//GEN-LAST:event_jChkStrawberryShakesActionPerformed

    private void jChkChocoMilkShakesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkChocoMilkShakesActionPerformed
        // Ini adalah kode jika ceklish di klik maka text field akan bisa diisi, jika tidak maka sebaliknya
        if (jChkChocoMilkShakes.isSelected()) {
            jTxtChocoMilkShakes.setEnabled(true);
            jTxtChocoMilkShakes.requestFocus();
            jTxtChocoMilkShakes.setText("");
        } else {
            jTxtChocoMilkShakes.setEnabled(false);
            jTxtChocoMilkShakes.setText("0");
        }
    }//GEN-LAST:event_jChkChocoMilkShakesActionPerformed

    private void jTxtChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtChangeActionPerformed

    private void jTxtMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtMoneyActionPerformed

    private void jBtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTotalActionPerformed
        // TODO add your handling code here:
        
        itemcost[0] = Double.parseDouble(jTxtFries.getName());
        itemcost[1] = Double.parseDouble(jTxtSalad.getName());
        itemcost[2] = Double.parseDouble(jTxtHamburger.getName());
        itemcost[3] = Double.parseDouble(jTxtOnionRings.getName());
        itemcost[4] = Double.parseDouble(jTxtChickenSalad.getName());
        itemcost[5] = Double.parseDouble(jTxtFishSandwich.getName());
        itemcost[6] = Double.parseDouble(jTxtCheeseSandwich.getName());
        itemcost[7] = Double.parseDouble(jTxtChickenSandwich.getName());
    }//GEN-LAST:event_jBtnTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FastFood().setVisible(true);
                //FastFood form = new FastFood();
                //int width = 790;
                //int height = 499;
                //int screenWidth = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
                //int screenHeight = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
                //int xPos = (screenWidth - width) / 2;
                //int yPos = (screenHeight - height) / 2;
            
                //form.setBounds(xPos, yPos, width, height);
                //form.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnTotal;
    private javax.swing.JCheckBox jChkBottleWater;
    private javax.swing.JCheckBox jChkCheeseSandwich;
    private javax.swing.JCheckBox jChkChickenSalad;
    private javax.swing.JCheckBox jChkChickenSandwich;
    private javax.swing.JCheckBox jChkChocoMilkShakes;
    private javax.swing.JCheckBox jChkChocolateMuffin;
    private javax.swing.JCheckBox jChkCoffee;
    private javax.swing.JCheckBox jChkCola;
    private javax.swing.JCheckBox jChkFishSandwich;
    private javax.swing.JCheckBox jChkFries;
    private javax.swing.JCheckBox jChkHamburger;
    private javax.swing.JCheckBox jChkHashBrown;
    private javax.swing.JCheckBox jChkOnionRings;
    private javax.swing.JCheckBox jChkOrange;
    private javax.swing.JCheckBox jChkPancakeSyrup;
    private javax.swing.JCheckBox jChkPineapleStick;
    private javax.swing.JCheckBox jChkSalad;
    private javax.swing.JCheckBox jChkStrawberryShakes;
    private javax.swing.JCheckBox jChkTea;
    private javax.swing.JCheckBox jChkToastedBagel;
    private javax.swing.JCheckBox jChkVanillaCone;
    private javax.swing.JCheckBox jChkVanillaShakes;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTxtBottleWater;
    private javax.swing.JTextField jTxtChange;
    private javax.swing.JTextField jTxtCheeseSandwich;
    private javax.swing.JTextField jTxtChickenSalad;
    private javax.swing.JTextField jTxtChickenSandwich;
    private javax.swing.JTextField jTxtChocoMilkShakes;
    private javax.swing.JTextField jTxtChocolateMuffin;
    private javax.swing.JTextField jTxtCoffee;
    private javax.swing.JTextField jTxtCola;
    private javax.swing.JTextField jTxtFishSandwich;
    private javax.swing.JTextField jTxtFries;
    private javax.swing.JTextField jTxtHamburger;
    private javax.swing.JTextField jTxtHashBrown;
    private javax.swing.JTextField jTxtMoney;
    private javax.swing.JTextField jTxtOnionRings;
    private javax.swing.JTextField jTxtOrange;
    private javax.swing.JTextField jTxtPancakeSyrup;
    private javax.swing.JTextField jTxtPineapleStick;
    private javax.swing.JTextField jTxtSalad;
    private javax.swing.JTextField jTxtStrawberryShakes;
    private javax.swing.JTextField jTxtSubTotal;
    private javax.swing.JTextField jTxtTax;
    private javax.swing.JTextField jTxtTea;
    private javax.swing.JTextField jTxtToastedBagel;
    private javax.swing.JTextField jTxtTotal;
    private javax.swing.JTextField jTxtVanillaCone;
    private javax.swing.JTextField jTxtVanillaShakes;
    // End of variables declaration//GEN-END:variables
}
